### ISSUE TITLE
In Windows I have an error running executables 

### ISSUE THREAD

**Issue by vadimtsushko** [filiph/dartbin#1]
I'm on Windows 10, Home Edition. Dart VM version: 1.23.0 (Fri Apr 21 03:13:00 2017) on "windows_x64"
go version go1.6.2 windows/amd64

After cloning repository I made simple script `sample.dart`

```
main() {
  print('Hello world');
}
```
Following instuctions (with a change in command to set `GOPATH` variable) I compiled that script into go_src.exe.

Runnung that script instead of `Hello world` I get stacktrace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x4018b3]

goroutine 1 [running]:
panic(0x51cd80, 0xc082002080)        C:/Programs/Go/src/runtime/panic.go:481 +0x3f4
main.run(0x0)        C:/ProjecAlt/dartbin/go_src/dartbin.go:49 +0x873
main.main()        C:/ProjecAlt/dartbin/go_src/dartbin.go:58 +0x1f
```

**Comment by filiph** [comment]
Hi, sorry! I haven't had the chance to test on Windows yet. I just committed a change (https://github.com/filiph/dartbin/commit/868e5950b9e27df3dffdf044384fa68ab2434b67) that will hopefully help me see what went wrong. Could you please git pull and try again?

**Comment by vadimtsushko** [comment]
Something changed after git pull. Now I get error 

```
C:\ProjecAlt\dartbin>go_src\go_src.exe
2017/06/09 22:17:54 exec: "C:\\Users\\Tsushko\\AppData\\Local\\Temp\\dartbin998448459\\dart": file does not exist
```

There should be `Hello world` in output

**Comment by filiph** [comment]
Aha! I can see two issues. Let's eliminate the first one:

Could you please either find dart.exe on your file system, or download it from https://www.dartlang.org/install/archive (it's part Dart SDK)? Then, when running step 2 of the [manual process](https://github.com/filiph/dartbin#manual-steps), please do something like `dart bin/main.dart --dart C:\full\path\to\dart.exe yourfile.snapshot`.

If you've done this already, please let me know.

**Comment by vadimtsushko** [comment]
With this I get new and proper system error message, in Russian (I'm on localized Windows)
Системе не удается найти указанный путь.

(System can not find file path, something like that)

**Comment by filiph** [comment]
Ok, I pushed two new commits, please `git pull` and try yet again.

Also, the localized error message, do you get it when running `dart bin/main.dart --dart C:\full\path\to\dart.exe yourfile.snapshot` or later when running `go_src.exe`?

**Comment by vadimtsushko** [comment]
`dart bin/main.dart --dart C:\full\path\to\dart.exe yourfile.snapshot` step run smoothly. And localized error message shows on go_src.exe output. Go pulling new commits

**Comment by vadimtsushko** [comment]
Great. That works. Now I have `Hello world` in my output

**Comment by vadimtsushko** [comment]
Will try it on some of my real apps tomorrow. Thank you very much

**Comment by vadimtsushko** [comment]
Well. It works even if i change `Hello world` message to `Привет мир` - it's Russian equivalent.
Not for I'm interested in such kind of localized output - (it works good in Windows 10, but still breaks in Windows Server 2012 for example) - but nice to know anyway.

**Comment by filiph** [comment]
Awesome! Great to know!
